### ISSUE TITLE
Part 2: Use dplyr instead of base R

### ISSUE THREAD

**Issue by pssachdeva** [dlab-berkeley/R-Fundamentals-Legacy#34]
This is up for discussion. However, I feel that functions like `subset` and `merge`, from base R, are not really used by practitioners these days. Instead, students would benefit most greatly from introduction to modern tools based on tidyverse packages such as dplyr. We can mention that these functions exist in base R, but we should instead do subsetting and merging with dplyr functions. This mimics how ggplot is introduced in Part 3.

**Comment by pattyf** [comment]
I would completely remove the section on `subset` in part 2 since it is a non-standard wrapper around bracket subsetting. Our R Data Wrangling workshops introduce the tidyverse so I think it may be overly complicated to introduce it in the fundamentals series. I think it should be mentioned in part 4 and folks should be encouraged to take the wrangling workshop series. They will run into base R in code that they find and in stackoverflow so I think we need to keep `merge` and other commonly used base R functions in the fundamentals. Open to discuss though!

**Comment by pssachdeva** [comment]
We could introduce the concepts using standard subsetting (but get rid of `subset`) and `merge`, but also show how to do a couple quick examples using `dplyr`. This is how it's done in `Part3.R` - the base R plotting is demonstrated, and then there's a switch to `ggplot`. Both of these parts could then serve as feeders to the Data Wrangling and Data Viz workshops, respectively.

As it stands, this lesson is a little short (we finished with extra time on 9/9), so I think it wouldn't hurt to add a little material, especially if we remove the section on `subset`.

**Comment by pattyf** [comment]
Sounds like a good plan! Make it so!
