### ISSUE TITLE
Move materials from Part 1 to Part 2

### ISSUE THREAD

**Issue by seanmperez** [dlab-berkeley/R-Fundamentals-Legacy#71]
There is bit of a bottleneck in Part1.R - Installation trouble shooting alone can take upwards of 30min-1hr.

A possible solution is to move some materials from Part1 to Part2 (especially anything dataframe related since it becomes redundant). This can make the focus of Part1 to help with troubleshooting getting started with R rather than getting deep into data structures. Will update this issue after observing Part2 today.

@Averysaurus

**Comment by pssachdeva** [comment]
I think this might generally only be an issue when the number of people attending is very large, as in the intensives. We might think about just increasing the number of assistants for the first hour of Part 1 when the number of people attending is >50. That way, everyone with installation issues can be placed in breakout rooms with enough assistants.

If this still remains an issue in later iterations of R Fundamentals, when the number of people is fewer (<50), then we can think about moving some material to Part 2.

**Comment by seanmperez** [comment]
Sounds good. I'll keep this on my radar and comment again when I teach the next round of R-fundamentals to see how it goes with more hands on instruction for installation.

**Comment by asteves** [comment]
@seanmperez I see that R-Fundamentals has been taught again. Did you have any updates on this?

**Comment by seanmperez** [comment]
@asteves @pssachdeva We experienced the same issue and Maya was also in accordance that we should move materials from part 1 to part 2. 

Day 2 went fine covering the additional material leftover from Day 1, supporting this idea.

A preliminary suggestion for a restructure is:

**Day1**
1. Installation (_40min - Make this explicit in the script?_)
2. Navigating RStudio
3. Variable Assignment
4. Functions and Arguments
5. Data Classes and Coercion (_remove factor? the concept doesn't stick in isolation, motivate it on day 3 using summary() on a character column_)
6. Data Structure (_change order to list -> vector -> matrix_)
7. End with motivation for dataframes, which is covered in Day 2

**Day2**
1. Use dataframe scripts from Part1
2. The rest of Part2 as is

Let me know if this is of interest, or if we should just keep as is!

**Comment by msamfair** [comment]
I totally agree with Sean! 
Even with 3 helpers for Part 1, upwards of 10 people will need 1-on-1 help with installation, and that will eat up the first hour of the workshop. I think the workshop instructions should still tell participants to install R and RStudio beforehand, because that minimizes the number of people who come unprepared. Plus, it helps if the unprepared already know what their sticking point is. We could have those who are ready read through something or explore the RStudio console on their own.

**Comment by asteves** [comment]
Just so I understand, do you think it needs to be 40 minutes because otherwise the room gets lost? 40 minutes feels like a very long time to just do installation. An implication of @msamfair is that the individuals who are fully installed and ready to go have to wait and do nothing. 

One possible option for them would be to add some "challenges" of exploration to keep engaged. @pssachdeva @seanmperez 

Also @seanmperez why do you suggest lists before vectors?

**Comment by pssachdeva** [comment]
Just discussed this with @asteves: we'll try moving dataframes and matrices to Part 2, and keeping lists in Part 1. Lists are shorter and pair more naturally with vectors.

I still think installation should not be taking this long, especially when the datahub is an available resource. This can be discussed on a separate issue, but it may be worth documenting what kinds of installation problems attendees are running into in order to streamline that process. 

I'll assign this issue to @asteves.

**Comment by seanmperez** [comment]
Hi @pssachdeva @asteves 

# Move end Part1 -> Part 2
Sounds good. Totally agree w/ moving dataframes/matrices to part 2. 

# Installation
Pointing attendees to datahub is a great solution as it works well with this workshop (for folks who can't get local to work). 

Can instructors demonstrate at the beginning of section how to navigate datahub? There can be many small hiccups such as:
1. How to open up RStudio/navigate directories in Datahub
2. If previously connected another project RStudio kinda freaks out, and you need to connect to the new project file.

I discussed with Sev that is a difficult tradeoff to move on before folks have finished installation, and can lead to lower retention. I am more than happy to writeup some common issues attendees experience, how to fix them, and reduce time spent on installation.

**Comment by asteves** [comment]
@seanmperez Please do. You can update the README which makes the most sense I think.
