### ISSUE TITLE
Improvements for Part 2

### ISSUE THREAD

**Issue by msamfair** [dlab-berkeley/R-Fundamentals-Legacy#85]
On line 13, the example Mac working directory path should be: "~/Desktop/R-Fundamentals-main" (the "-main" is missing). We could also add a comment that explains the "cannot change working directory" error means the path they tried does not exist.
On line 52, there should be quotation marks around "here" in install.packages(here)
Also just a thought - I think people are confused by the here() function. It comes right after they learn what a working directory and path name are, and they've just been told to be very precise about path names before being presented with this confusing shortcut. Maybe we should save here() for a Data Wrangling workshop?

**Comment by asteves** [comment]
@msamfair The second issue is fixed in the code on the [main branch now](https://github.com/dlab-berkeley/R-Fundamentals/blob/main/lessons/Part2.R). 

@pssachdeva the first issue seems to be a consequence of downloading the zip file instead of using ssh or the command line. I'll fix the lesson to reflect.

**Comment by asteves** [comment]
Second issue is fixed by [this commit](https://github.com/dlab-berkeley/R-Fundamentals/commit/e1aa71ed0f2a374d0bbfc0d051fefc0b5fbc7a0c)

**Comment by pssachdeva** [comment]
I'm worried about people running into more problems without the `here` package because the data is in a different directory. With something like `here`, I'd rather expose attendees to a tricky concept that "just works" (i.e., if they leave the code alone, it will work fine), especially when it comes to something like this, which builds good coding practices.

We could try clarifying what exactly `here` is doing: it's creating a filepath in a smart way, but this isn't directly apparent in the lesson (the path is passed to the `read.csv` function right away). So, maybe a couple lines showing the output of `here()`, `here(data)`, etc. would be helpful. These serve as sanity checks to demonstrate that things work the way you expect them too.

**Comment by pssachdeva** [comment]
After discussing further with @asteves, let's instead rely on the Rproj to set the working directory to ensure people don't run into issues. Then, we'll have the discussion on working directories, and turn the `here` text into a bonus, take home challenge. 

@asteves will turn this into a separate issue.

**Comment by pssachdeva** [comment]
@asteves: can we close this if the first issue is already handled and the second issue is its own issue now?

**Comment by asteves** [comment]
@pssachdeva Was going to close it and the separate issue at the same time with the PR. If you don't think that's necessary, feel free to close now.

**Comment by pssachdeva** [comment]
@asteves OK, sounds good, I'll leave it to you to close.
